services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
    volumes:
      - "./web/src:/app/src"
      - "./web/index.html:/app/index.html"
      - "./web/vite.config.ts:/app/vite.config.ts"
    user: "0:0"
    depends_on:
      - backend

  backend:
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true
    build:
      context: .
      dockerfile: Dockerfile
    command: gow run /app/main.go
    volumes:
      - "./pkg:/app/pkg"
      - "./aws:/root/.aws/"
    #ports:
    #  - 8080:8080
    environment:
      PG_URL: postgres://pguser:pgpassword@db:5432/pguser?search_path=public
      S3_ENDPOINT: http://127.0.0.1:8333
    env_file: .env

  weed:
    image: chrislusf/seaweedfs # use a remote image
    restart: always
    ports:
      - 8333:8333
    command: "server -dir=/data -s3 -idleTimeout=0"

    volumes:
      #- "/mnt/hdd/seaweed:/data"
      - "./appdata/seaweed:/data"
      - "./s3.json:/etc/seaweedfs/config.json"
#      - "./filer.toml:/etc/seaweedfs/filer.toml"

# Use postgres/example user/password credentials
  db:
    image: postgres
#    network_mode: host
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      #- "./db/base.sql:/docker-entrypoint-initdb.d/0-base.sql"
      - "./db/base.sql:/docker-entrypoint-initdb.d/0-base.sql"
      - "./db/data.sql:/docker-entrypoint-initdb.d/1-data.sql"
      - ./appdata/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/5432"
      interval: 1s
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_USER: pguser

  #daemon:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.daemon
  #  environment:
  #    #CRON_SAMPLE: '* * * * * echo 1 minute cron'
  #    CRON_ANOTHER_SAMPLE: '0 2 * * * python3 /app/sync_s3.py'
  #  depends_on:
  #    db:
  #      condition: service_healthy
  #      restart: true

  web:
    image: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - backend
      - frontend