services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
      VITE_S3_ENDPOINT: http://localhost:9000
    volumes:
      - "./web/src:/app/src"
      - "./web/index.html:/app/index.html"
      - "./web/vite.config.ts:/app/vite.config.ts"
    user: "0:0"
    depends_on:
      - backend

  backend:
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true
    build:
      context: .
      dockerfile: Dockerfile
    command: gow run /app/main.go
    volumes:
      - "./pkg:/app/pkg"
      - "./scripts:/app/scripts"
      - "./assets:/app/assets"
      - "./main.go:/app/main.go"
      #- "./aws:/root/.aws"
    #ports:
    #  - 8080:8080
    environment:
      EXTERNAL_S3_ENDPOINT: http://127.0.0.1:9000
      INTERNAL_S3_ENDPOINT: http://minio:9000
      ROOT_PASSWORD: "rootpassword"
      S3_ROOT_ACCESS_KEY: admin
      S3_ROOT_SECRET_KEY: changeme
      PG_HOST: db
      PG_PORT: 5432
      PG_DATABASE: pguser
      PG_USER: pguser
      PG_PASSWORD: pgpassword
      PG_SCHEMA: public
      WORKER_PG_HOST: db
      WORKER_PG_PORT: 5432
      WORKER_PG_DATABASE: pguser
      WORKER_PG_USER: pguser
      WORKER_PG_PASSWORD: pgpassword
      WORKER_PG_SCHEMA: public

# Use postgres/example user/password credentials
  db:
    image: postgres
#    network_mode: host
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      #- "./db/base.sql:/docker-entrypoint-initdb.d/0-base.sql"
      - "./db/base.sql:/docker-entrypoint-initdb.d/0-base.sql"
      #- "./db/data.sql:/docker-entrypoint-initdb.d/1-data.sql"
      - ./appdata/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/5432"
      interval: 1s
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_USER: pguser

  web:
    image: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - backend
      - frontend

  minio:
    image: quay.io/minio/minio
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - ./appdata/minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server --console-address :9001 /data --console-address :9001
